# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('third_party_auth', '0021_sso_id_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAuthMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('puid', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'third_party_auth_social_auth_mapping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersocialauthmapping',
            unique_together=set([('uid', 'puid')]),
        ),
    ]
