# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20171207_0259'),
        ('oauth_dispatch', '0002_restrictedapplication_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedApplication_33',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_org_associations', models.ManyToManyField(to='organizations.Organization')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
