# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_dispatch', '0003_restrictedapplication_33'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedapplication_33',
            name='organization_type',
            field=models.CharField(choices=[(b'content_provider', 'Content Provider'), (b'user_provider', 'User Provider')], default=b'content_provider', max_length=32),
        ),
    ]
